# Generated by Django 6.1.1 on 2026-10-06 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_superuser_staff_access'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='devicesession',
            new_name='accounts_de_user_id_45e55c_idx',
            old_name='acct_ds_user_revoked_idx',
        ),
        migrations.RenameIndex(
            model_name='devicesession',
            new_name='accounts_de_user_id_edad7e_idx',
            old_name='acct_ds_user_device_idx',
        ),
    ]
