# Generated by Django 6.1.1 on 2026-10-03 14:06

import core.assets
import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='pdf',
            field=models.FileField(storage=core.assets.private_media_storage, upload_to='products/reports/', validators=[core.uploads.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='file',
            field=models.FileField(storage=core.assets.public_media_storage, upload_to='products/images/', validators=[core.uploads.validate_image_file]),
        ),
    ]
