# Generated by Django 6.1.1 on 2026-10-03 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_labreport_pdf_alter_productimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='group',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='is_subfact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16),
        ),
        migrations.AddField(
            model_name='nutritionfact',
            name='note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='banned_ingredients_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='guidance',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='hidden_sugars_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='note',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='nutritionist_note',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='serving_basis',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='shares_printed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='sugar_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='unit_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='relatedproduct',
            name='kind',
            field=models.CharField(choices=[('flavor', 'Flavor'), ('related', 'Related')], default='related', max_length=20),
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('detail', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
