# Generated by Django 6.1.1 on 2026-10-08 21:25

import core.assets
import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_merchandising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='pdf',
            field=models.FileField(storage=core.assets.private_media_storage, upload_to='products/reports/', validators=[core.uploads.validate_report_file]),
        ),
    ]
